/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jqidpdjtmltvtrasosla"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxaWRwZGp0bWx0dnRyYXNvc2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTU5MzUsImV4cCI6MjA3ODA5MTkzNX0.j8x-98b1mW6jiG1OOXvBxMw98IU-22NBPKZvBXYLLwc"